require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :disable_input_output_paths => true
use_frameworks!
#use_modular_headers!
#:modular_headers => false

source 'https://github.com/genesys/dx-sdk-specs-dev'
source 'https://github.com/CocoaPods/Specs'

target 'MobileDxRNSample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  #pod 'genesys-mobiledx-chat-rn-module', :path => '../../RN/mobile-genesys-chat-rn-module'
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
#  use_flipper!()

#  post_install do |installer|
#    react_native_post_install(installer)
#  end
  
#  post_install do |installer|
#    react_native_post_install(installer)
#
#    installer.pods_project.targets.each do |target|
#      target.build_configurations.each do |config|
#        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
#      end
#
#      if (target.name&.eql?('FBReactNativeSpec'))
#        target.build_phases.each do |build_phase|
#          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
#            target.build_phases.move(build_phase, 0)
#          end
#        end
#      end
#    end
#  end
  
end
